# Generated by Django 2.2.5 on 2019-09-26 06:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('avaliation_id', models.AutoField(primary_key=True, serialize=False)),
                ('avaliation_grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('avaliation_text', models.TextField()),
                ('avaliation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'avaliation',
                'ordering': ['avaliation_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'db_table': 'department',
                'ordering': ['department_name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AddField(
            model_name='student',
            name='sobrenome',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.AutoField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_nome', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
                ('subject_nmo', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None)])),
                ('subject_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
            options={
                'db_table': 'subject',
                'ordering': ['subject_department', 'subject_nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nota', models.DecimalField(decimal_places=2, default=5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Department')),
            ],
            options={
                'db_table': 'professor',
                'ordering': ['nota'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_grades', models.DecimalField(decimal_places=2, default=5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('class_avaliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Avaliation')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
            options={
                'db_table': 'class_id',
                'ordering': ['class_avaliation'],
            },
        ),
        migrations.AddField(
            model_name='avaliation',
            name='avaliation_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Professor'),
        ),
        migrations.AddField(
            model_name='avaliation',
            name='avaliation_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
        migrations.AddField(
            model_name='avaliation',
            name='avaliation_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.Course'),
        ),
    ]
